# frozen_string_literal: true

require 'gtk4'

require_relative 'loamp/adw'

# Ordered by dependency: metadata underpins artwork and tracks, which the
# player and the UI are built on.
require_relative 'loamp/file_uri'
require_relative 'loamp/http/rate_limiter'
require_relative 'loamp/http/client'
require_relative 'loamp/metadata'
require_relative 'loamp/metadata/reader'
require_relative 'loamp/artwork'
require_relative 'loamp/cover_art/miss_log'
require_relative 'loamp/cover_art/musicbrainz'
require_relative 'loamp/cover_art/archive'
require_relative 'loamp/cover_art/fetcher'
require_relative 'loamp/art_cache'
require_relative 'loamp/playback_settings'
require_relative 'loamp/lyrics/document'
require_relative 'loamp/lyrics/lrc_parser'
require_relative 'loamp/lyrics/lrclib'
require_relative 'loamp/lyrics/resolver'
require_relative 'loamp/lyrics/cache'
require_relative 'loamp/podcast/feed'
require_relative 'loamp/podcast/parser'
require_relative 'loamp/podcast/client'
require_relative 'loamp/podcast/opml'
require_relative 'loamp/podcast/store'
require_relative 'loamp/podcast/downloader'
require_relative 'loamp/provider'
require_relative 'loamp/provider/subsonic'
require_relative 'loamp/provider/jellyfin'
require_relative 'loamp/listenbrainz'
require_relative 'loamp/lastfm'
require_relative 'loamp/scrobbler'
require_relative 'loamp/musicbrainz_artist'
require_relative 'loamp/radio/station'
require_relative 'loamp/radio/browser'
require_relative 'loamp/radio/graph_store'
require_relative 'loamp/radio/store'
require_relative 'loamp/radio/station_queue'
require_relative 'loamp/radio/similarity'
require_relative 'loamp/radio/graph_layout'
require_relative 'loamp/track'
require_relative 'loamp/playlist'
require_relative 'loamp/visualizer_presets'
require_relative 'loamp/audio_engine'
require_relative 'loamp/visualizer'
require_relative 'loamp/crossfade_engine'
require_relative 'loamp/player'

require_relative 'loamp/library'
require_relative 'loamp/library/schema'
require_relative 'loamp/library/search'
require_relative 'loamp/library/scanner'

require_relative 'loamp/mpris'
require_relative 'loamp/mpris/variant'
require_relative 'loamp/mpris/adapter'
require_relative 'loamp/mpris/service'

require_relative 'loamp/ui/style'
require_relative 'loamp/ui/playback_menu'
require_relative 'loamp/ui/library_name_factory'
require_relative 'loamp/ui/track_info'
require_relative 'loamp/ui/lyrics_view'
require_relative 'loamp/ui/player_controls'
require_relative 'loamp/ui/playlist_view'
require_relative 'loamp/ui/library_view'
require_relative 'loamp/ui/radio_view'
require_relative 'loamp/ui/podcast_view'
require_relative 'loamp/ui/provider_view'
require_relative 'loamp/ui/graph_view'
require_relative 'loamp/ui/visualizer_view'
require_relative 'loamp/ui/secondary_views'
require_relative 'loamp/ui/keyboard_shortcuts'
require_relative 'loamp/ui/playback_observers'
require_relative 'loamp/ui/main_window'
require_relative 'loamp/application'

# Main module for the LOAMP music player
module Loamp
  VERSION = '1.0.0'
end
